### ISSUE TITLE
Wrong CWL version

### ISSUE THREAD

**Issue by sivkovic** [mskcc-cwl/msisensor_0.5#1]
https://github.com/mskcc-cwl/msisensor_0.5/blob/39cd621aab04f370abee131cd61dce38ebd081df/msisensor.cwl#L2

It should be `v1.0`.

**Comment by allanbolipata** [comment]
Just changed it, already on `master`; `tempo` should be updated, too.

https://github.com/mskcc-cwl/msisensor_0.5/blob/master/msisensor.cwl#L2
